### ISSUE TITLE
test_gen_basic_pause_location is a brittle test

### ISSUE THREAD

**Issue by clementzach** [onnela-lab/forest#105]
test_gen_basic_pause_location sometimes fails with what looks like [small differences in rounding](https://github.com/onnela-lab/forest/runs/6463803296?check_suite_focus=true). Whether the test fails or passes seems to be pretty random, as it will switch from failing to passing without me making any changes to the underlying code. 

Rounding to 2 decimal points instead of 3 seems like it would fix the issue, but I wanted to reach out to @GeorgeEfstathiadis to see if that would be an appropriate fix.

**Comment by GeorgeEfstathiadis** [comment]
I checked the difference in Google Maps and the difference does not seem to be significant, so feel free to changing the rounding to 2 decimals to fix it.
