### ISSUE TITLE
Jasmine entropy is negative when num_sig_places is 1

### ISSUE THREAD

**Issue by clementzach** [onnela-lab/forest#114]
Commit hash (the first line of output from `git show`): 9e206cf63bb95a4a52fe208aa059af25341d26c2

**Describe the bug**

For days when num_sig_places is 1, entropy is calculated to be a small negative number by jasmine. 

Entropy is defined in the documentation as $-\sum_{i} p_i*log(p_i)$

In the case when there is 1 significant location, $p_1 = 1$, and this is $- 1*log(1) = 1*0 = 0$

However, in the [code](https://github.com/onnela-lab/forest/blob/9e206cf63bb95a4a52fe208aa059af25341d26c2/forest/jasmine/traj2stats.py#L656), entropy is calculated as -sum(p * np.log(p + 0.00001))

I believe that using p + 0.00001 rather than p is helpful in cases where one of the values in the p vector may be 0, in order to avoid calculating $log(0) = -\infty$. However, having negative values of entropy

**To reproduce**
download_folder = "user_data"
zf = msync.download(Keyring, "q97eL0qkYiOnPUn0tsQRd1A3", "7yeqzbpz", ["gps"], time_start = "2000-01-01", time_end = "2022-06-01")
zf.extractall(download_folder)
from forest.constants import Frequency
from forest.jasmine.traj2stats import gps_stats_main

gps_stats_main(
    study_folder = download_folder,
    output_folder = "gps_full_output",
    tz_str = "America/New_York",
    frequency = Frequency.DAILY,
    participant_ids = ["7yeqzbpz"],
    save_traj = True)

Then, look at the file. 

**Observed behavior**
| year | month | day | obs_duration       | obs_day             | obs_night           | home_time          | dist_traveled | max_dist_home        | radius              | diameter           | num_sig_places | entropy                | total_flight_time   | av_flight_length | sd_flight_length   | av_flight_duration    | sd_flight_duration   | total_pause_time   | av_pause_duration  | sd_pause_duration  |
|------|-------|-----|--------------------|---------------------|---------------------|--------------------|---------------|----------------------|---------------------|--------------------|----------------|------------------------|---------------------|------------------|--------------------|-----------------------|----------------------|--------------------|--------------------|--------------------|
| 2021 | 2     | 16  | 14.986341111130185 | 0.0                 | 14.986341111130185  | 24.0               | 0.0           | 0.002040556882214018 | 0.0                 | 0.0                | 1              | -9.999950000398841e-06 | 0.0                 | 0.0              | 0.0                | 0.0                   | 0.0                  | 24.0               | 12.0               | 2.9863411111301845 |
| 2021 | 2     | 17  | 0.0                | 0.0                 | 0.0                 |                    |               |                      |                     |                    |                |                        |                     |                  |                    |                       |                      |                    |                    |                    |
| 2021 | 2     | 18  | 0.0                | 0.0                 | 0.0                 |                    |               |                      |                     |                    |                |                        |                     |                  |                    |                       |                      |                    |                    |                    |
| 2021 | 2     | 19  | 0.0                | 0.0                 | 0.0                 |                    |               |                      |                     |                    |                |                        |                     |                  |                    |                       |                      |                    |                    |                    |
| 2021 | 2     | 20  | 0.0                | 0.0                 | 0.0                 |                    |               |                      |                     |                    |                |                        |                     |                  |                    |                       |                      |                    |                    |                    |
| 2021 | 2     | 21  | 0.0                | 0.0                 | 0.0                 |                    |               |                      |                     |                    |                |                        |                     |                  |                    |                       |                      |                    |                    |                    |
| 2021 | 2     | 22  | 0.0                | 0.0                 | 0.0                 |                    |               |                      |                     |                    |                |                        |                     |                  |                    |                       |                      |                    |                    |                    |
| 2021 | 2     | 23  | 0.0                | 0.0                 | 0.0                 |                    |               |                      |                     |                    |                |                        |                     |                  |                    |                       |                      |                    |                    |                    |
| 2021 | 2     | 24  | 0.3333333333333333 | 0.20555555555555555 | 0.12777777777777777 | 23.505122848484252 | 2.643         | 0.8299738289021972   | 0.02848857406404119 | 0.8494582145193528 | 1              | -9.999950000398841e-06 | 0.16598000625769296 | 0.0550625        | 0.1134670301324721 | 0.0034579167970352704 | 0.004274272773650962 | 23.834019993742306 | 0.2109205309180735 | 1.0536062652198164 |

**Expected behavior**
I believe that entropy for these values should be 0 rather than -9.999950000398841e-06.

**Additional context**

I created a [branch](https://github.com/onnela-lab/forest/tree/jasmine_entropy_zero) with a fix for this, but I need feedback from someone familiar with entropy before merging it.

**Comment by GeorgeEfstathiadis** [comment]
I am not familiar with how entropy works and I am not the one that wrote the code for it so I don't think I can help with this.

**Comment by clementzach** [comment]
Sounds good @GeorgeEfstathiadis , I'll unassign you.

**Comment by martakarass** [comment]
Hi @clementzach I do not seem to be able to access the branch you linked (404 error). 

I agree with your observations and likely origin of the small constant added, and a fix could add the constant only to elements of `p` that are equal `0`. 

Side note/fun fact, I wonder if this is my python notebook, or this code is really supposed to be printing *minus* 0.0?

```
import numpy as np
p = np.array([1])
p_replaced0 = [0.000001 if v == 0 else v for v in p]
entropy = -sum(p_replaced0 * np.log(p_replaced0))
entropy
```
```
-0.0
```

**Comment by clementzach** [comment]
My mistake, I re-did the link. 

You can also see the permalink to the lines that I changed [here](https://github.com/onnela-lab/forest/blob/e6e18c1b052323f371dcf278d1ad04afc24b710a/forest/jasmine/traj2stats.py#L657)
