### ISSUE TITLE
Jasmine running despite no GPS data

### ISSUE THREAD

**Issue by clementzach** [onnela-lab/forest#128]
Commit hash (the first line of output from `git show`): 7fceb601a5083848190c25acb041f977e8e0b6ca

**Describe the bug**
Jasmine is attempting to run forest on an individual despite recognizing that the user does not have sufficient data

**To reproduce**
import sys
beiwe_ids = ["g4wkenld"]
study_id = "B6GXRdjYVcnObzvs2eVh3Czc"
dest_dir = "test_data"
server = "studies"
time_start = "2008-01-01"
time_end = None
data_streams = ["gps"]

# import .py file located in another directory if needed
import mano
sys.path.insert(0, '/Volumes/SanDisk/onnela_lab/keyring_files')

import keyring_studies
kr = mano.keyring(None)

import os

from helper_functions import download_data

download_data(kr, study_id, dest_dir, users = beiwe_ids, time_start = "2008-01-01", 
                      time_end = None, data_streams = None)

import forest.jasmine.traj2stats
from forest.jasmine.traj2stats import Frequency

output_dir = "gps_output"
tz_str = "America/New_York"
option = Frequency.BOTH
save_traj = True 
places_of_interest = None
place_threshold = None
save_log = False

forest.jasmine.traj2stats.gps_stats_main(
    dest_dir, output_dir, tz_str, option, save_traj,
    save_log = save_log,places_of_interest = places_of_interest, 
    threshold = place_threshold, participant_ids = beiwe_ids
)

**Observed behavior**
Downloading data for g4wkenld
User g4wkenld: There are no gps data in range.
User: g4wkenld
Read in the csv files ...
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [4], in <module>
     33 place_threshold = None
     34 save_log = False
---> 37 forest.jasmine.traj2stats.gps_stats_main(
     38     dest_dir, output_dir, tz_str, option, save_traj,
     39     save_log = save_log,places_of_interest = places_of_interest, 
     40     threshold = place_threshold, participant_ids = beiwe_ids
     41 )

File /Volumes/SanDisk/opt/anaconda3/envs/python_3_8/lib/python3.8/site-packages/forest/jasmine/traj2stats.py:1000, in gps_stats_main(study_folder, output_folder, tz_str, frequency, save_traj, parameters, places_of_interest, save_log, threshold, split_day_night, person_point_radius, place_point_radius, time_start, time_end, participant_ids, all_memory_dict, all_bv_set, quality_threshold)
    998     parameters.h = parameters.r
    999 if orig_w is None:
-> 1000     parameters.w = np.mean(data.accuracy)
   1001 # process data
   1002 mobmat1 = GPS2MobMat(
   1003     data, parameters.itrvl, parameters.accuracylim,
   1004     parameters.r, parameters.w, parameters.h
   1005 )

File /Volumes/SanDisk/opt/anaconda3/envs/python_3_8/lib/python3.8/site-packages/pandas/core/generic.py:5583, in NDFrame.__getattr__(self, name)
   5576 if (
   5577     name not in self._internal_names_set
   5578     and name not in self._metadata
   5579     and name not in self._accessors
   5580     and self._info_axis._can_hold_identifiers_and_holds_name(name)
   5581 ):
   5582     return self[name]
-> 5583 return object.__getattribute__(self, name)

AttributeError: 'DataFrame' object has no attribute 'accuracy'

**Expected behavior**
Jasmine should stop running after it returns the warning `User g4wkenld: There are no gps data in range.`

**Additional context**
After we fix this, we should add a test that verifies this behavior so it is not inadvertently reintroduced.

**Comment by GeorgeEfstathiadis** [comment]
Hi @clementzach, I am unable to replicate the data using your code above. I wanted to ask when you download the data for the user how does his directory structure look like? Is there an empty `gps` folder or there is no such folder at all?
