### ISSUE TITLE
error running sycamore on server deployment

### ISSUE THREAD

**Issue by biblicabeebli** [onnela-lab/forest#130]
commit hash in use: 2402c6f73d3e562dc346e39ba0408cd9f4607857

stack trace:
```
ValueError: You are trying to merge on float64 and object columns. If you wish to proceed you should use pd.concat
  File "services/celery_forest.py", line 148, in celery_run_forest
    TREE_TO_FOREST_FUNCTION[task.forest_tree](**params_dict)
  File "forest/sycamore/base.py", line 215, in get_submits_for_tableau
    agg_data = aggregate_surveys_config(
  File "forest/sycamore/common.py", line 421, in aggregate_surveys_config
    df_merged = agg_data.merge(
  File "pandas/core/frame.py", line 9345, in merge
    return merge(
  File "pandas/core/reshape/merge.py", line 107, in merge
    op = _MergeOperation(
  File "pandas/core/reshape/merge.py", line 704, in __init__
    self._maybe_coerce_merge_keys()
  File "pandas/core/reshape/merge.py", line 1257, in _maybe_coerce_merge_keys
    raise ValueError(msg)
```

**Comment by biblicabeebli** [comment]
or the commit hash is c055ba718b9d7b16dd1d3d52926b8d952729c246?

**Comment by clementzach** [comment]
@biblicabeebli I pushed a commit that should fix this. 

could you point me to the study/config file that is returning this error? I want to add a test for that.

**Comment by biblicabeebli** [comment]
This is from a sentry error: https://sentry.io/organizations/onnela-lab/issues/3514160226/?project=133863&query=is%3Aunresolved

has this useful label: participant sqg92gyz of Study "Onnela Lab_Forest Test Study"

**Comment by biblicabeebli** [comment]
@GeorgeEfstathiadis this is a stack trace bug to review due to https://github.com/onnela-lab/beiwe-discussions/issues/164

Dumb question - do you know how to re-run a forest task?

**Comment by GeorgeEfstathiadis** [comment]
I don't know how to run forest tasks in the server in general, so not re-runs either.

**Comment by biblicabeebli** [comment]
new error!

can be seen at https://studies.beiwe.org/studies/944/forest/tasks
```
  File "forest/sycamore/base.py", line 215, in get_submits_for_tableau
    agg_data = aggregate_surveys_config(
  File "forest/sycamore/common.py", line 414, in aggregate_surveys_config
    config_surveys = parse_surveys(config_path)
  File "forest/sycamore/common.py", line 324, in parse_surveys
    for q in s["content"]:
```

**Comment by biblicabeebli** [comment]
Update: we need to resolve an issue where new parameters are not json serializeable before we can resolve/check if these are resolved.

**Comment by hydawo** [comment]
> new error!
> 
> can be seen at https://studies.beiwe.org/studies/944/forest/tasks
> 
> ```
>   File "forest/sycamore/base.py", line 215, in get_submits_for_tableau
>     agg_data = aggregate_surveys_config(
>   File "forest/sycamore/common.py", line 414, in aggregate_surveys_config
>     config_surveys = parse_surveys(config_path)
>   File "forest/sycamore/common.py", line 324, in parse_surveys
>     for q in s["content"]:
> ```

This error is still occurring in latest commit (0bd8e80)

**Comment by biblicabeebli** [comment]
these issues can be debugged on staging now, but its not on production servers yet.

**Comment by biblicabeebli** [comment]
This issue is out of date and I'm going to close it, tracking exactly this error is a fool's errand, we will just repost if it occurs.
