### ISSUE TITLE
trying to run Oak to process Accelerometer data - file structure demanded keeps changing

### ISSUE THREAD

**Issue by Aryan181** [onnela-lab/forest#131]
First time I run it, it gives the error - `Errno 2] No such file or directory: '/Users/amahindra/Documents/data-accel/i/accelerometer'`

Another time I run it, I get the following error - `[Errno 2] No such file or directory: '/Users/amahindra/Documents/data-accel/5/accelerometer'`

Is the Oak script stable?

**Comment by biblicabeebli** [comment]
@Aryan181 what commit/branch are you on?
@MStraczkiewicz Oak is you, right?

**Comment by Aryan181** [comment]
I'm running the script locally using the latest forest version and Oak from here https://forest.beiwe.org/en/latest/oak.html#installation-instruction

**Comment by MStraczkiewicz** [comment]
Hi, is your data collected with Beiwe?

**Comment by Aryan181** [comment]
Seems like this line -> `file_list = os.listdir(source_folder)` is having an issue.

**Comment by Aryan181** [comment]
Fixed that issue. Now having a new issue - ```
File "/Users/amahindra/opt/anaconda3/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 674, in _extract_index
    raise ValueError("All arrays must be of the same length")
```

**Comment by Aryan181** [comment]
@MStraczkiewicz

**Comment by MStraczkiewicz** [comment]
Thanks for letting me know. I'm addressing the array length issue and will let you know when it's fixed.

**Comment by Aryan181** [comment]
Ok, we're trying to run a study @ UW (University of Washington) soon. Do you have an estimate on when it'll be done?

**Comment by MStraczkiewicz** [comment]
The bug had been addressed on my end and it's now being reviewed by Forest maintainers. It should be out shortly. I'll keep you posted.

**Comment by biblicabeebli** [comment]
This is not the oak issue that I thought it was, I believe that is actually in an email.
@GeorgeEfstathiadis is this issue resolved

**Comment by GeorgeEfstathiadis** [comment]
There are no open PR requests in Forest for Oak. I assume @MStraczkiewicz handled in PR #132  but forgot to link it to this issue.
@MStraczkiewicz was this handled in a PR that was merged in Forest? Can we close it?

**Comment by MStraczkiewicz** [comment]
I think we can close it.

**Comment by GeorgeEfstathiadis** [comment]
Thank you @MStraczkiewicz !
