### ISSUE TITLE
Discrepancy in dist_traveled and max_dist_home units between hourly and daily summaries

### ISSUE THREAD

**Issue by clementzach** [onnela-lab/forest#135]
Commit hash (the first line of output from `git show`):
6c14f8d1f74866d54d2e890fc9b1fa8db0fd25fb

**Describe the bug**
The units in dist_traveled and max_dist_home vales returned from jasmine are inconsistent between daily and hourly summaries.

**Expected behavior**
Either dist_traveled values should be reported in kilometers for hourly summaries, or we should update the documentation to reflect that the units are different at different levels of resolution. 

**Additional context**
I'm happy to make a PR for this, but wanted to get others' feedback before doing so.

**Comment by GeorgeEfstathiadis** [comment]
Thank you for noticing this @clementzach. I will create a PR to update the values in kilometers and add you to review it.
