### ISSUE TITLE
file_list and file_ind order mismatch in oak:base.py

### ISSUE THREAD

**Issue by jadraketx** [onnela-lab/forest#175]
Commit hash (the first line of output from `git show`):
commit fdaffea4d82ccc16f908455e92e54cbcaa646ab3 (HEAD -> develop, origin/develop, origin/HEAD)

**Describe the bug**
Beginning on line 531 of base.py in oak module, the following identifies the indices of the files that should be read in for a given d_datetime:
``` python
# find file indices for this d_ind
file_ind = [i for i, x in enumerate(dates_shifted)  if x == d_datetime]
```
The enumeration is over `dates_shifted`, which is derived from `dates`, which is derived from `file_dates`. `file_dates` is sorted on line 475. `file_dates` is based on `file_list`, which contains a list of all accelerometer files for a given user. Note: `file_list` is never sorted. The code to read the raw data for a given day begins on line 541:

``` python
# load data for a given day
for f in file_ind:
    logger.info("File: %d", f)

    # read data
    file_path = os.path.join(source_folder, file_list[f])
    data = pd.concat([data, pd.read_csv(file_path)], axis=0)
```
The code above iterates over the file indices, but indexes `file_list` to grab the actual file name. However, `file_list` is not sorted and therefore does not have the same order as `dates_shifted`. As a result, the incorrect files are read.

**To reproduce**
Inspect `dates_shifted` and `file_list` and compare ordering.

**Observed behavior**
Accelerometer data for a specified day is not being read in correctly.

**Expected behavior**

**Additional context**
I believe a quick fix would be to sort `file_list` right after it is created on line 467 of base.by.
``` python
file_list = os.listdir(source_folder)
###proposed fix
file_list.sort()
```

**Comment by GeorgeEfstathiadis** [comment]
Thank you, will implement your solution!
