### ISSUE TITLE
FutureWarnings in Sycamore

### ISSUE THREAD

**Issue by hackdna** [onnela-lab/forest#211]
To reproduce:
```
pytest forest/sycamore/tests
```
Observed output:
```
forest/sycamore/tests/test_functions.py: 55 warnings
  /Users/ils475/code/onnelalab/forest/forest/sycamore/read_audio.py:136: FutureWarning: get_duration() keyword argument 'filename' has been renamed to 'path' in version 0.10.0.
  	This alias will be removed in version 1.0.
    all_durations.append(librosa.get_duration(

forest/sycamore/tests/test_functions.py: 55 warnings
  /Users/ils475/code/onnelalab/forest/forest/sycamore/read_audio.py:136: FutureWarning: PySoundFile failed. Trying audioread instead.
  	Audioread support is deprecated in librosa 0.10.0 and will be removed in version 1.0.
    all_durations.append(librosa.get_duration(
```
Expected output: no warnings

Notes:

Starting from version 1.1.0 libsndfile supports MP3 format (https://github.com/libsndfile/libsndfile/blob/master/docs/FAQ.md#q20--why-doesnt-libsndfile-support-mp3-q020)
This will probably require upgrading to Ubuntu 24.04 LTS (https://packages.ubuntu.com/search?libsndfile)

**Comment by clementzach** [comment]
@hackdna thanks for bringing this up. 

The first warning is resolved in this pr (https://github.com/onnela-lab/forest/pull/222)

The second warning is not able to be resolved at this time. The warning will appear from librosa (https://github.com/librosa/librosa/issues/1015) until their dependent library libsndfile gains the ability to read mp4 files. Progress on libsndfile's ability to read mp4 files can be seen here (https://github.com/libsndfile/libsndfile/issues/389)

**Comment by hackdna** [comment]
Thanks for addressing the first warning.

Does the second warning mean that librosa version 1.0 would potentially lose the ability to read mp3 files (at least until libsndfile gains that ability)? Does Forest need to be able to process mp3 files?

**Comment by clementzach** [comment]
Yes, librosa plans to deprecate using audioread. If they do so, forest's reading of mp4 files will be deprecated and there will be no information for duration spent on audio surveys. But, it seems like the deprecation doesn't have any super active plans--more information about that is here: https://github.com/librosa/librosa/issues/1456

**Comment by hackdna** [comment]
OK, thank you for looking in to this. I'll close this issue for now.
