### ISSUE TITLE
GPS raw data error

### ISSUE THREAD

**Issue by MMel099** [onnela-lab/forest#247]
I have identified a new error with GPS data that can cause downstream errors with the Jasmine analysis. When generating the raw data GPS csv files, some rows inexplicably get duplicated in a way that messes up the format (screenshot below). Starting from row 243, rows get duplicated in a way that the duplicates have more columns than the original rows. This then causes a "ParserError: Error tokenizing data. C error: Expected 6 fields in line XXX, saw 7" when running Jasmine.

![Image](https://github.com/onnela-lab/forest/assets/63422396/db0075e5-eb86-461e-8764-d1424df239b7)

One way to fix this would be to iterate over all the GPS files, searching and pruning rows with duplicate timestamps. I am starting to look into Mano for the source of the problem but the code is quite advanced.

**Comment by MMel099** [comment]
@GeorgeEfstathiadis have you seen anything like this before?

**Comment by GeorgeEfstathiadis** [comment]
No I have not seen such an issue with raw GPS data before, but this feels like a bug with data collection. Maybe @biblicabeebli would know what this is about?

**Comment by biblicabeebli** [comment]
It's a data processing bug.
I can't find it, I made an issue and assigned everyone on it about these extra columns getting injected but that I thought I had fixed it.
I don't know what's up that's causing it to not even have commas there, that's *really* strange but also so is Excel so who knows.

Gimme participant ids and their server, I will clear and rerun all of the affected user's data to clear it out. Hard to say exactly how long that takes, but definitely by the next day.

**Comment by MMel099** [comment]
I did a big Forest task on all of the data in the Yale study. A few participants had this error in both Jasmine and Oak so accelerometer is likely also affected. txo6lahs is my personal id in the Yale study and the first injected row happened in the file from 03/23/24 at 22:00:00 (started collecting data in January on this id).
[study](https://studies.beiwe.org/studies/952/forest/tasks)
IDs: l2e3gzih, gq4s82qs, mhwnmw12, txo6lahs, ra5aq9d5, e15hkfui

**Comment by biblicabeebli** [comment]
Just kicked off the reprocessing for those users.

buuuuuut I screwed it up and unintentionally removed identifiers..... I'll go fix that...

**Comment by biblicabeebli** [comment]
ok those are added too.

**Comment by MMel099** [comment]
Looks like it worked! I created a forest task for Oak and Jasmine on txo6lahs which is my id and it worked. I'll try the others locally. Quick question - do you know why some Forest tasks on the dashboard have a "download output data" button and others do not? Thanks

**Comment by biblicabeebli** [comment]
I will have to look into that participant, the only concerns I can think of would be with iOS participants.

Download data link - when I started typing I thought I knew the answer, but I don't. I will have to check this as well.

**Comment by MMel099** [comment]
I think the data for id ra5aq9d5 came in a little slowly but is all there now. We can probably close this issue. I'm wondering if the original data injection issue that this thread was opened about may have happened in other studies too? I only found these bugged ids when doing a full Forest run on the Yale study.

**Comment by biblicabeebli** [comment]
I would say no, don't worry about it, just let me know if anything comes up.  Forest should not be updated to handle this malformed data.

The cause was transient.
- There was a ~36ish-maybe hour period where - "uploading data from an hour for which we already had some data" - would cause those columns/lines to get injected/duplicated.
- After I fixed it I had to make a guess about how far back in "time as defined as the timestamp of the data point" I had to go in order to hopefully clear out all malformed data.
- This is not deterministic because a device can be off in the wilderness for a week and then upload a bunch of data from the past week all at once.
- All data was affected on all servers and so far we have this report of it.

This was your github issue, so you can make the call on closing it, I don't have anything else for you.

**Comment by hydawo** [comment]
This looks good. TLDR: there might be one or two users who had data in the small window of time that this error was occurring and had not uploaded it prior to Eli applying the fix above. If we encounter this again, Eli can fix the specific user/time period again. 

Closed.

**Comment by jprince127** [comment]
Hello!

I wanted to add to this thread and say that I am also seeing a few participants with this data error for a different study.
@biblicabeebli would you be able to clear the affected user's data like you did with Max's study? The errors begin on 3/22:

[study](https://eu.beiwe.org/view_study/8)
IDs: u895ifsz, cmzge55q

Thank you so much!

**Comment by biblicabeebli** [comment]
@jprince127 responded in email thread, could you please close this thread when we the process is confirmed finished and fixed

**Comment by jprince127** [comment]
Yes the data has been fixed!

**Comment by jprince127** [comment]
Hello!

I'm seeing this data error in a different study in both accelerometer and gps data.
@biblicabeebli could you clear this as well? Thank you so much! :

[study](https://eu.beiwe.org/view_study/7)
Study ID : tRIMFFw52g5VgdMnhH01xU51
Patient ID:   lgquy9dn, 5kirsiiu, wkcafrmb

**Comment by biblicabeebli** [comment]
I did the thing!
gps + accelerometer data has been cleared on those three participants, it will now be reprocessed. Should be a few hours, holler at me if its not there by.... 10am?

**Comment by biblicabeebli** [comment]
@jprince127 when it is done, can you please sanity-check the bytes count of the dashboard values with a day's data manually for one of those participants?  Pick a random day, other than the first or last day, where there is data in every data stream.

The bytes value shoouuuld match the sum of file sizes for that day quite closely - reminder those values on the dashboard are contained in a timezone-day according to the study's timezone so you will have to download the data and shift it to match.

(File size may include the bytes of the file name/file path, I'm looking for a value that's way off.)

**Comment by jprince127** [comment]
Hello!

There is one more data error in this study in the accelerometer data.
@biblicabeebli could you clear this please? The errors begin on 3/22. Thank you so much once again! :

[study](https://eu.beiwe.org/view_study/12)
Study ID : tRIMFFw52g5VgdMnhH01xU51
Patient ID: 5kirsiiu

Additionally, I've checked the byte count of the dashboard against the dashboard values, and they seem to be similar values - nothing that is way off so far, but I will keep checking more closely as well.

**Comment by biblicabeebli** [comment]
(Ah, I got a notification because a message with an @ of me in it was edited)

@jprince127 just let me know if I didn't do one.  No need to respond to this message if I'm caught up..

**Comment by biblicabeebli** [comment]
The corrupted source data was resolved, this issue was sitting around unclosed. closing.
