### ISSUE TITLE
Document: Don't understand the time unit of summary statistics 

### ISSUE THREAD

**Issue by YUHUINI1995** [onnela-lab/forest#263]
I'm having difficulty understanding the time units of the summary statistics listed in [this documentation](https://forest.beiwe.org/en/latest/jasmine.html#list-of-summary-statistics).

Could someone help me understand them? For example, what are the units of obs_duration and total_flight_time, and how can I convert them into seconds or minutes?

<img width="1296" alt="image" src="https://github.com/user-attachments/assets/c5cfb7c8-6a1e-44d4-a729-32dd03335d74">

**Comment by YUHUINI1995** [comment]
@hackdna Could you or your team member answer this question? Thanks!

**Comment by hackdna** [comment]
@YUHUINI1995, thanks for reaching out. I think @GeorgeEfstathiadis should be able to answer these questions.

**Comment by YUHUINI1995** [comment]
@hackdna Thank you.

@GeorgeEfstathiadis Could you help answer these questions?

**Comment by GeorgeEfstathiadis** [comment]
@YUHUINI1995 the measures in the `hourly` summary file related to time and duration are all in minutes.

**Comment by YUHUINI1995** [comment]
> @YUHUINI1995 the measures in the `hourly` summary file related to time and duration are all in minutes.

Thanks. How about the `daily` summary file? Is it also in minute or in hour?

**Comment by GeorgeEfstathiadis** [comment]
The `daily` should be in hours.

**Comment by YUHUINI1995** [comment]
> The `daily` should be in hours.

Gotcha. Thanks for your reply.

**Comment by hackdna** [comment]
Thanks @GeorgeEfstathiadis! Would you mind adding units to the relevant variables in the [docs](https://forest.beiwe.org/en/latest/jasmine.html#list-of-summary-statistics)?

**Comment by JiaxinCCC** [comment]
Hi @GeorgeEfstathiadis,

I have a follow-up question. I generated the output file using the `daily` setting, and below is the result
<img width="1182" alt="image" src="https://github.com/user-attachments/assets/a34b58aa-2400-4626-b5d5-ac7ea5c975f1">

As you can see, some values of `obs_day` and `obs_night` are larger than 12, which seems unusual given the definition provided on the website. Could you explain why this might be happening?

<img width="718" alt="image" src="https://github.com/user-attachments/assets/a420d594-50c1-456a-9f9d-95e06ceff190">

**Comment by GeorgeEfstathiadis** [comment]
Hi @JiaxinCCC, this is a bug which we would need to investigate. Can you share the study and participant Beiwe ID you used to get this summary file as well as the code script you ran? And then I can look into this further.

**Comment by JiaxinCCC** [comment]
> Hi @JiaxinCCC, this is a bug which we would need to investigate. Can you share the study and participant Beiwe ID you used to get this summary file as well as the code script you ran? And then I can look into this further.

Hi @GeorgeEfstathiadis, thanks for your reply! I ran the code below using `Python 3.11` and `forest==0.1.1`.

```python
from forest.jasmine.traj2stats import Frequency, Hyperparameters, gps_stats_main

data_dir = "data/onnela_lab_gps_testing/"
output_dir = "gps_output_daily"
tz_str = "America/New_York"
frequency = Frequency.DAILY
save_traj = True
gps_stats_main(data_dir, output_dir, tz_str, frequency, save_traj)
```

The data was downloaded from [this repository](https://github.com/mkiang/beiwe_data_sample/tree/master), based on [this tutorial](https://github.com/onnela-lab/forest/blob/develop/tutorials/forest_usage.ipynb).

The ID is `6b38vskd` under the folder `onnela_lab_gps_testing`. Let me know if you need any additional information.

**Comment by GeorgeEfstathiadis** [comment]
Hi @JiaxinCCC, I have created a PR to fix this bug (at least for the extreme values seen in row 1).

Some of these `obs_day` and `obs_night` can be a bit above 12 due to rounding errors. I.e. if there is an observed pause that starts at 6:45pm and ends at 7:10pm, it will count as 25 minutes of observed time at daytime (while 10 of those minutes were actually nighttime). This is why it is possible to see observed times be above 12 hours in day or night, but it shouldn't be too common, especially when dealing with real world data where missingness is more profound.

**Comment by JiaxinCCC** [comment]
@GeorgeEfstathiadis I’ve re-run the code with your fix and can confirm that the extreme value in row 1 has been resolved. Thanks for your help!

<img width="1076" alt="image" src="https://github.com/user-attachments/assets/8c0e56dd-18a2-4ddb-972e-d0b7baa58420" />
