### ISSUE TITLE
Python 3.6 sunset end of 2021

### ISSUE THREAD

**Issue by biblicabeebli** [onnela-lab/forest#40]
Python 3.6 goes out of support, e.g. security updates plus general widespread availability, at the end of this year.

If you are wondering about python's release cadence you can review it here: [https://www.python.org/dev/peps/pep-0602/#implementation](https://www.python.org/dev/peps/pep-0602/#implementation)

The beiwe-backend repo will be shifting to Python 3.8.x - this is purely based on the platform versions available to us on AWS Elastic Beanstalk servers as dictated by this website at this moment in time: [https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html#platforms-supported.python](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html#platforms-supported.python).

It is _extremely unlikely_ that such an upgrade to the runtime version will result in any compatibility issues for forest, but I'm not the expert on that.

The forest runtime environment as controlled by the beiwe-backend is trivially portable up to python 3.8, and more recent versions - python 3.9 is the current release, python 3.10 is slated for release on October 4th - is workable given some lead-time.  I am always a proponent of upgrading to the latest and greatest, so if anything at all looks nice for forest in python 3.9 or 3.10 we can do it.

For your perusal and consideration:
[https://docs.python.org/3/whatsnew/3.7.html](https://docs.python.org/3/whatsnew/3.7.html)
[https://docs.python.org/3/whatsnew/3.8.html](https://docs.python.org/3/whatsnew/3.7.html)
[https://docs.python.org/3/whatsnew/3.9.html](https://docs.python.org/3/whatsnew/3.7.html)

The python 3.10's what's-new page does not have an identical url/page structure, but there is this nearly-identical one - I have left this as plaintext for copy-pasting because I suspect it will change on us come Oct 4: 
https://docs.python.org/3.10/whatsnew/3.10.html

**Comment by biblicabeebli** [comment]
In a meeting yesterday we decided "might as well do 3.8 because newer is better."
And so it begins....

**Comment by hackdna** [comment]
Note that regressions are a risk because there is no test suite.

**Comment by biblicabeebli** [comment]
python 3.8 is live on the github repo and on all onnela lab servers.  Data processing, including forest, now runs on python 3.8.

**Comment by hackdna** [comment]
Static type checking fails with Python 3.8: #59
