### ISSUE TITLE
comm_logs_summaries() throws UnboundLocalError if texts data is empty while calls data is not empty

### ISSUE THREAD

**Issue by martakarass** [onnela-lab/forest#68]
I was using forest on "Public Sample Beiwe Dataset" from Zenodo ([source](https://zenodo.org/record/1188879#.Yex2eljMJTY)) and I ran into an error when running `log_stats_main()`. I see it tracks to `comm_logs_summaries()` which throws an error b/c a local variable does not get defined if texts data is empty while calls data is not empty. There are 0 texts and 1 call in this data. 

I use Python 3.8.12.
I observed the same output as shown below when running on:
(a) Python environment that has forest `main` branch installed,
(b) Python environment that has forest `develop` branch installed. 

Reproducible example: 

```python
import pandas as pd
from forest.willow.log_stats import comm_logs_summaries
from platform import python_version

print(python_version())

ID = "6b38vskd"
text_data = pd.DataFrame.from_dict({})
call_data = pd.DataFrame.from_dict(
    {'timestamp': {0: 1454428647649},
     'UTC time': {0: '2016-02-02T15:57:27.649'},
     'hashed phone number': {0: 'ZlGtb-SRRIgOcHLBD02d2_F049naF0YZbCx_CeP7jss='},
     'call type': {0: 'Missed Call'},
     'duration in seconds': {0: 0}}
)
stamp_start = 1453837206
stamp_end = 1454634000
tz_str = "America/New_York"
option = "daily" 

stats_pdframe = comm_logs_summaries(ID, text_data, call_data, stamp_start, stamp_end, tz_str,option)
```
```
3.8.12
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
/var/folders/sk/c14blb7s493_7lgzdq0m3sjm0000gn/T/ipykernel_51047/4226467727.py in <module>
     19 option = "daily"
     20 
---> 21 stats_pdframe = comm_logs_summaries(ID, text_data, call_data, stamp_start, stamp_end, tz_str,option)

~/opt/anaconda3/envs/forest_run/lib/python3.8/site-packages/forest/willow/log_stats.py in comm_logs_summaries(ID, df_text, df_call, stamp_start, stamp_end, tz_str, option)
     91         if option == 'daily':
     92             newline = [year, month, day, num_in_call, num_out_call, num_mis_call, num_uniq_in_call, num_uniq_out_call,
---> 93                   num_uniq_mis_call, total_time_in_call, total_time_out_call, num_s, num_r, num_mms_s, num_mms_r, num_s_tel,
     94                   num_r_tel, total_char_s, total_char_r,text_reciprocity_incoming,text_reciprocity_outgoing]
     95         if option == 'hourly':

UnboundLocalError: local variable 'num_s' referenced before assignment
```
Also, for future, what is the best way to show programmatically which forest commit/download date I am using? 

FYI @patricknnamdi (who also graciously shared code with group/me to learn how to use forest)

**Comment by hackdna** [comment]
Thanks for reporting this. What should the default value for `num_s` (and other similar variables like `num_r`) be if text data is empty?

You can get the current commit with `git rev-parse HEAD`.

**Comment by martakarass** [comment]
Hi @hackdna I think they should be set to `0` (as they represent the number of texts sent, number of texts received, etc.), but I am tagging @kwcarlso so she could confirm.

**Comment by kwcarlso** [comment]
@martakarass not sure if I fully understand the question, but yes text and call data can be disabled. However, the standard settings are for them to be turned on. The caveat is that this is only applicable to Android phones, so if there are no Android phones in a study, we will not collect any communication log data. Does that answer your question?

**Comment by martakarass** [comment]
Hi @kwcarlso thanks! What do you think should be a default value of statistics such "number of texts sent" and similar in case there is no texts data? Are we OK to out `0` in the output (_regardless_ whether the texts communication log data were (a) available for OS and not disabled, (b) available for OS but disabled, (c) not available for OS)?

**Comment by kwcarlso** [comment]
My guess is that would make sense but I would confirm with @jponnela

**Comment by hackdna** [comment]
FWIW, it looks like Jasmine is using `pd.NA` for missing data:
https://github.com/onnela-lab/forest/blob/main/forest/jasmine/traj2stats.py#L122
and
https://github.com/onnela-lab/forest/blob/main/forest/jasmine/traj2stats.py#L155

**Comment by jponnela** [comment]
Hi @martakarass @hackdna @kwcarlso. I think we want to be able to distinguish between there being no call activity (i.e., call count, for example, is 0) and call / communication logs not being available at all. So if I'm understanding this question correctly, it seems to me that the default should be NA. What do others think?

**Comment by martakarass** [comment]
@hackdna "linked a pull request that will close this issue 2 days ago" - just to confirm, can I close this issue? Thanks!

**Comment by hackdna** [comment]
I've requested your review on that PR! :) If you approve the changes I will merge the code and that will automatically close this issue.
