### ISSUE TITLE
Set up documentation using Sphinx

### ISSUE THREAD

**Issue by hackdna** [onnela-lab/forest#98]
- [x] Set up a Read the Docs project
- [x] Set up a [custom domain](https://docs.readthedocs.io/en/stable/custom_domains.html)
- [x] Copy the content from the wiki to https://github.com/onnela-lab/forest/tree/develop/docs
- [x] Add https://forest.beiwe.org to the About section of the repo
- [x] Add doc build [badges](https://docs.readthedocs.io/en/stable/badges.html) to the top level README.md
- [x] Disable the wiki
- [x] Add instructions on how to build the docs

**Comment by hackdna** [comment]
@biblicabeebli please set up a CNAME record `forest.beiwe.org` with target `readthedocs.io`

**Comment by biblicabeebli** [comment]
okay i've set up the cname
